name: BYOND Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BYOND_MAJOR: 515
  BYOND_MINOR: 1645
  SPACEMAN_DMM_VERSION: suite-1.6
  PYTHON_VERSION: 3.6.8

jobs:
  run_linters:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Run Linters
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ hashFiles('dependencies.sh') }}
          restore-keys: |
            ${{ runner.os }}-spacemandmm-
      - name: Restore Rust cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('tools/ci/ci_dependencies.sh')}}
          restore-keys: |
            ${{ runner.os }}-rust-
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install setuptools
          pip3 install pillow
          chmod +x tools/ci/install_node.sh
          chmod +x tools/ci/install_spaceman_dmm.sh
          bash tools/ci/install_node.sh
          bash tools/ci/install_spaceman_dmm.sh dreamchecker
      - name: Run Linters
        run: |
          chmod +x tools/ci/check_filedirs.sh
          chmod +x tools/ci/check_changelogs.sh
          chmod +x tools/ci/check_grep.sh
          bash tools/ci/check_filedirs.sh tgstation.dme
          bash tools/ci/check_changelogs.sh
          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
          tgui/bin/tgui --lint
          bash tools/ci/check_grep.sh
          python3 tools/validate_dme.py tgstation.dme
          touch ${GITHUB_WORKSPACE}/output-annotations.txt
          ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1 || true
      - name: Annotate Lints
        uses: yogstation13/DreamAnnotate@v2
        if: always()
        with:
          outputFile: output-annotations.txt

  compile_all_maps:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Compile Maps
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libstdc++6:i386 libssl1.1:i386
      - name: Compile All Maps
        run: |
          chmod +x tools/ci/install_byond.sh
          chmod +x tools/ci/dm.sh
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          python3 tools/ci/template_dm_generator.py
          tgui/bin/tgui --build
          bash tools/ci/dm.sh -DCIBUILDING -DCITESTING -DALL_MAPS tgstation.dme

  run_all_tests:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Integration Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libstdc++6:i386 libssl1.1:i386
      - name: Setup database
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'CREATE DATABASE tg_ci;'
          mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
          mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
          mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql
      - name: Install rust-g
        run: |
          chmod +x tools/ci/install_rust_g.sh
          bash tools/ci/install_rust_g.sh
      - name: Compile and run tests
        run: |
          chmod +x tools/ci/install_byond.sh
          chmod +x tools/ci/dm.sh
          chmod +x tools/ci/run_server.sh
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          tgui/bin/tgui --build
          bash tools/ci/dm.sh -DCIBUILDING tgstation.dme
          bash tools/ci/run_server.sh

  test_windows:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Restore BYOND cache
        uses: actions/cache@v4
        with:
          path: C:\\byond
          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}
          restore-keys: |
            ${{ runner.os }}-build-${{ secrets.CACHE_PURGE_KEY }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Compile
        run: |
          pip install pillow
          pwsh tools/ci/build.ps1
      - name: Create artifact
        run: |
          md deploy
          bash tools/deploy.sh ./deploy
      - name: Deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy
